name: 构建admin-server

on:
  repository_dispatch:
    types: [admin-server]

#on:
#  push:
#    branches:
#      - dev
#  pull_request:
#    branches:
#      - dev

env:
  # 当前项目名称
  project_name: bronya #${GITHUB_REPOSITORY#*/}
  # 格式化的push请求则不执行
  format_message: alibaba/p3c格式化

jobs:
  build-code:
    name: 构建bronya-admin-server容器
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: 发布maven仓库
        run: | 
          mvn package -Pjib -pl bronya-admin-server -am -DskipTests -Dmaven.test.skip=true -s /home/runner/work/${{ env.project_name }}/${{ env.project_name }}/settings.xml